import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";
import { getCategories } from "@/data";
import AuthButtons from "@/components/AuthButtons";
import { Toaster } from "@/components/ui/toaster";

const kanit = Kanit({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategories();

  return (
      <html lang="en">
        <body className={`${kanit.className} flex flex-col min-h-screen`}>
          <Header categories={categories}>
            <AuthButtons />  
          </Header>
          {children}
          <Footer />
          <Toaster />
          </body>
      </html>
  );
}
